export const flashcardData = [
  { front: "Searching", back: "Finding whether a target value is present and, if it is, identifying its position." },
  { front: "Linear Search", back: "Checks elements one by one from the start until the target is found or the data ends." },
  { front: "Linear Search Requirement", back: "None. Linear search works on sorted or unsorted data." },
  { front: "Linear Search Best Case", back: "O(1), when the target is the first element checked." },
  { front: "Linear Search Worst Case", back: "O(N), when the target is last or is not present." },
  { front: "When to Use Linear Search", back: "Use it for a small or unsorted collection, especially when only one search is needed." },
  { front: "Binary Search", back: "Compares the target with the middle element and repeatedly discards half of the remaining search range." },
  { front: "Binary Search Requirement", back: "The data must already be sorted." },
  { front: "Binary Search Best Case", back: "O(1), when the first middle element is the target." },
  { front: "Binary Search Worst Case", back: "O(log N), because the remaining search range is halved at every step." },
  { front: "Binary Search Space", back: "O(1) for an iterative version and O(log N) call-stack space for a recursive version." },
  { front: "Binary Search and Arrays", back: "Arrays suit binary search because any middle index can be accessed in O(1) time." },
  { front: "Binary Search and Linked Lists", back: "Binary search is a poor fit because reaching a linked list's middle element requires traversal." },
  { front: "Sorting", back: "Arranging elements into a defined order, such as ascending or descending order." },
  { front: "Bubble Sort", back: "Repeatedly compares adjacent elements and swaps those that are out of order." },
  { front: "Bubble Sort Pass", back: "After one ascending pass, the largest value in the unsorted section reaches its final position." },
  { front: "Bubble Sort Complexity", back: "Best case O(N) with an early-stop flag; average and worst case O(N^2)." },
  { front: "Bubble Sort Stability", back: "Stable: equal elements keep their original relative order." },
  { front: "Selection Sort", back: "Finds the minimum value in the unsorted section and swaps it into the next sorted position." },
  { front: "Selection Sort Complexity", back: "O(N^2) in the best, average, and worst cases." },
  { front: "Selection Sort Swaps", back: "At most one swap per pass, giving O(N) swaps in total." },
  { front: "Selection Sort Stability", back: "The standard implementation is unstable because a long-distance swap can reorder equal values." },
  { front: "Insertion Sort", back: "Builds a sorted section by shifting larger values right and inserting the next value into its correct position." },
  { front: "Insertion Sort Complexity", back: "Best case O(N); average and worst case O(N^2)." },
  { front: "When to Use Insertion Sort", back: "Use it for small or nearly sorted datasets." },
  { front: "Insertion Sort Stability", back: "Stable in its standard form because equal values do not need to move past one another." },
  { front: "Merge Sort", back: "Splits data into smaller halves, sorts them, and merges the sorted halves back together." },
  { front: "Merge Sort Complexity", back: "O(N log N) in the best, average, and worst cases." },
  { front: "Merge Sort Array Space", back: "O(N) auxiliary space for the temporary array used during merging." },
  { front: "Merge Sort Stability", back: "Stable when equal elements from the left half are chosen first during merging." },
  { front: "Stable Sort", back: "A sort that preserves the original relative order of elements with equal keys." },
  { front: "In-Place Sort", back: "A sort that uses only a small, constant amount of extra storage beyond the input." },
  { front: "Divide and Conquer", back: "Break a problem into smaller subproblems, solve them, and combine their results. Merge Sort and Binary Search use this idea." },
  { front: "Binary Search Loop Invariant", back: "If the key is present, it must be somewhere in the inclusive range low through high." },
  { front: "Safe Binary Midpoint", back: "Use low + (high - low) / 2 so low + high cannot overflow before division." },
  { front: "Recursive Binary Search Base Case", back: "Return -1 when low > high; the candidate range is empty." },
  { front: "Bubble Sort Loop Invariant", back: "After each ascending pass, the sorted suffix contains the largest values in final positions." },
  { front: "Selection Sort Loop Invariant", back: "Before pass i, indices 0 through i - 1 contain the smallest values in final order." },
  { front: "Insertion Sort Loop Invariant", back: "At the start of pass i, indices 0 through i - 1 form a sorted prefix." },
  { front: "Merge Precondition", back: "The two runs given to merge must already be sorted." },
  { front: "Merge Sort Recursion Depth", back: "O(log N), because each recursive level roughly halves the range." },
  { front: "Iterative vs Recursive Binary Space", back: "Iterative uses O(1) auxiliary space; recursive uses O(log N) call-stack space." },
  { front: "Trace Table Discipline", back: "Record the state after the event named by the question: each probe, comparison, swap, pass, insertion, or merge." },
];
