export const flashcardData = [
  { front: "Package", back: "A named namespace that groups related Java types and contributes to their fully qualified names." },
  { front: "Fully qualified class name", back: "The package name plus simple class name, such as java.util.Scanner." },
  { front: "What an import changes", back: "It lets one source file use a type's simple name during name resolution." },
  { front: "What an import does not do", back: "It does not copy a class, compile it, install a dependency, or configure the runtime classpath." },
  { front: "Automatic package", back: "Types in java.lang, including String, Math, and System, are available without explicit imports." },
  { front: "Wildcard boundary", back: "package.* imports types directly in that package, not types in its subpackages." },
  { front: "Package declaration position", back: "The first non-comment statement, before imports and type declarations." },
  { front: "Source path rule", back: "Folders below the source root mirror the dotted package name." },
  { front: "Public class filename", back: "A public top-level class must be stored in a file with the same case-sensitive name and .java extension." },
  { front: "Package-private access", back: "No modifier: accessible inside the same package, not from an unrelated class in another package." },
  { front: "private", back: "Accessible only inside the declaring top-level class." },
  { front: "public", back: "Accessible wherever the declaring type itself is accessible." },
  { front: "javac -d classes", back: "Writes generated class files under the classes root, creating package subdirectories." },
  { front: "javac -sourcepath src", back: "Tells the compiler where package-structured source dependencies begin." },
  { front: "java -cp classes", back: "Tells the launcher that compiled package lookup begins at the classes directory." },
  { front: "Running a packaged class", back: "Use its fully qualified name, for example java -cp classes app.Tester." },
  { front: "Could not find or load main class", back: "First check the classpath root and the fully qualified target class name." },
  { front: "package ... does not exist", back: "Check package spelling, declaration/path agreement, and the compiler's source or classpath root." },
];
