import { array, code, escape, figure, levels, list, player, recursionTree, stack, table } from './visuals.mjs';
import { search, sort } from './simulations.mjs';
import { JAVA, runnable } from './java.mjs';
import { REFERENCE_SECTIONS, REFERENCE_SHA256 } from './reference-content.mjs';
import { algorithmOverview, packageOverview } from './overviews.mjs';
import { topicQuiz } from './quizzes.mjs';
import { focusedMergeLesson } from './merge-lesson.mjs';
import { barLesson } from './bar-lessons.mjs';
import { ALGORITHM_INTRODUCTIONS, algorithmIntroduction, algorithmReason } from './introductions.mjs';
import { finalMergeWalkthrough } from './merge-map.mjs';

const SORT_INPUT = [4, 2, 5, 1, 3];
const MERGE_INPUT = [63, 29, 72, 85, 18, 49, 3, 54];
const LINEAR_INPUT = [63, 29, 85, 72, 18, 42, 23, 54, 8, 32];
const BINARY_INPUT = [8, 18, 23, 29, 34, 42, 54, 63, 72, 85];
const section = (id, title, body) => ({ id, title, body });
const note = (text) => `<aside class="note">${text}</aside>`;
const terms = (items) => table(['Term', 'Meaning in this chapter'], items, 'Vocabulary');
const question = (prompt, answer) => `<details class="question"><summary>${prompt}</summary><div class="answer">${answer}</div></details>`;
const rowsOfSearch = (run) => run.steps.map((s, i) => [i + 1, ...(run.kind === 'binary' ? [s.low, s.high, s.i] : [s.i]), s.value, s.decision]);
const headersOfSearch = (kind) => kind === 'binary' ? ['Probe', 'low', 'high', 'mid', 'Value', 'Evaluated conditions and update'] : ['Check', 'i', 'arr[i]', 'Evaluated condition and result'];
const allSorted = (values) => values.map((_, i) => i);
const searchFrames = (run) => run.steps.map((s, i) => ({ title: `${run.kind === 'binary' ? 'Probe' : 'Check'} ${i + 1}: index ${s.i}`, visual: figure(array(run.input, { active: [s.i], sorted: s.match ? [s.i] : [], discarded: run.input.flatMap((_, j) => run.kind === 'binary' ? j < s.low || j > s.high ? [j] : [] : j < s.i ? [j] : []), labels: run.kind === 'binary' ? { [s.low]: 'low', [s.high]: s.low === s.high ? 'low/high' : 'high', [s.i]: s.i === s.low && s.i === s.high ? 'low/mid/high' : 'mid' } : { [s.i]: s.match ? 'found' : 'i' } }), `Key ${run.key}; ${run.kind === 'binary' ? `inclusive candidate range ${s.low}..${s.high}` : 'checks proceed left to right'}.`), explanation: s.decision, print: true }));

export const REGISTRY = [
  ['linear-search', 'Linear Search', 'sorting-and-searching', 'linear'],
  ['binary-search', 'Binary Search', 'sorting-and-searching', 'binary'],
  ['bubble-sort', 'Bubble Sort', 'sorting-and-searching', 'bubble'],
  ['selection-sort', 'Selection Sort', 'sorting-and-searching', 'selection'],
  ['insertion-sort', 'Insertion Sort', 'sorting-and-searching', 'insertion'],
  ['merge-sort', 'Merge Sort', 'sorting-and-searching', 'merge'],
  ['built-in-packages-and-imports', 'Built-in Packages and Imports', 'packages', 'imports'],
  ['creating-a-package', 'Creating a Java Package', 'packages', 'package'],
  ['compiling-and-running', 'Compiling and Running Packages', 'packages', 'build'],
].map(([slug, title, chapter, kind]) => ({ slug, title, chapter, kind, id: `${chapter}/${slug}`, sourceRoutes: [`/docs/sem3/csi247/${chapter}/notes/${slug}`, ...(['bubble', 'selection'].includes(kind) ? [`/docs/sem3/csi247/${chapter}/notes/bubble-and-selection-sort`] : [])] }));

const SORT_INFO = {
  bubble: {
    summary: 'Compare neighbours, swap inverted pairs, and lock the largest active value on the right after each pass.',
    definition: 'Bubble sort is a comparison sort that repeatedly scans adjacent pairs. In ascending order it exchanges a pair only when the left value is larger than the right value.',
    plain: 'Read the cards from left to right. Every time a bigger card sits before a smaller one, exchange them. A large card can travel many cells in one pass, while a small card may move left only one cell in that pass.',
    idea: 'After one complete pass, the largest active value has reached the last active position. The next pass ignores that fixed suffix.',
    vocabulary: [['Adjacent', 'Two neighbouring indexes j and j + 1.'], ['Swap', 'Exchange two values using a temporary variable.'], ['Pass', 'One sweep through the still-active adjacent pairs.'], ['Sorted suffix', 'The final positions already proved correct.'], ['swapped flag', 'A Boolean reset before each pass; a whole pass with no change permits early termination.']],
    invariant: 'At the start of pass p (zero based), the last p positions hold the p largest values in final order.',
    costs: [['Best', 'O(n)', 'Already sorted input: one pass makes n - 1 comparisons and no swaps.'], ['Average / worst', 'O(n²)', 'A reverse-order array needs many shrinking sweeps.'], ['Auxiliary space', 'O(1) iterative; O(n) recursive worst case', 'A temporary swap value versus a chain of calls.'], ['Stable / in place', 'Yes / yes', 'Strict > avoids crossing equals; values are exchanged inside the input.'], ['Adaptive', 'Yes in this optimized version', 'The swapped flag enables early stop.']],
    descending: 'Change arr[j] > arr[j + 1] to arr[j] < arr[j + 1]. Each pass then locks the smallest active value on the right.',
    mistakes: [['Loop to j < arr.length', 'arr[j + 1] reaches an invalid index.', 'Use j < arr.length - 1 - pass.'], ['Declare swapped only once', 'An earlier swap prevents later early termination.', 'Reset it to false before every pass.'], ['Swap on >=', 'Equal records may cross and lose stability.', 'Swap only strictly inverted pairs.'], ['Stop after one non-swap', 'Only that pair is ordered.', 'Stop after an entire pass with no swaps.']],
    use: 'Useful for small teaching examples and for recognizing adjacent-pair logic. Already sorted input benefits from early stop; large unsorted arrays are better suited to an O(n log n) algorithm.',
  },
  selection: {
    summary: 'Scan the entire unsorted suffix, remember its minimum index, and swap that minimum into the next final position.',
    definition: 'Selection sort partitions an array into a sorted prefix and unsorted suffix. Each pass selects the smallest suffix value and exchanges it with the first suffix position.',
    plain: 'Find the smallest remaining card before you move anything. Put it in the next empty final position. Repeat with the cards still waiting.',
    idea: 'The scan proves which value belongs at index i; one swap puts it there. A new smaller candidate updates an index during the scan rather than causing an immediate swap.',
    vocabulary: [['i', 'The final position being filled.'], ['min', 'Index of the best candidate seen so far, not the candidate value.'], ['j', 'Index currently being scanned.'], ['Sorted prefix', 'Positions 0..i-1 already contain the smallest i values.'], ['Selection', 'Finding a minimum before one final swap.']],
    invariant: 'Before pass i, positions 0..i-1 contain the i smallest values in final order. During the scan, min names the smallest value seen from i through j.',
    costs: [['Best / average / worst', 'O(n²)', 'Every suffix is fully scanned, even on sorted input.'], ['Key comparisons', 'n(n - 1)/2', 'Lengths n - 1, n - 2, ... , 1.'], ['Swaps', 'At most n - 1', 'At most one actual exchange per pass; self-swaps are skipped.'], ['Auxiliary space', 'O(1) iterative; O(n) recursive', 'Only index variables and a temporary value in the iterative form.'], ['Stable / in place / adaptive', 'No / yes / no', 'A long swap can cross equal records; scanning does not shrink with presortedness.']],
    descending: 'Select the maximum instead: change arr[j] < arr[min] to arr[j] > arr[min]. The prefix then grows in descending order.',
    mistakes: [['Set min = arr[i]', 'Treats a value as an index.', 'Set min = i, then compare arr[j] and arr[min].'], ['Swap every new minimum immediately', 'Changes the taught selection procedure and swap counts.', 'Finish the full scan, then swap once.'], ['Always swap min and i', 'Adds redundant writes when they are the same.', 'Skip the swap when min == i.'], ['Call it stable', 'Long-distance exchanges can cross equal values.', 'Use a tagged duplicate counterexample.']],
    use: 'Useful when swaps are more costly than comparisons and the input is small. It offers few swaps but still requires quadratic comparisons.',
  },
  insertion: {
    summary: 'Save the next key, shift larger prefix values one position right, and insert the key into the gap.',
    definition: 'Insertion sort builds a sorted prefix one value at a time. It inserts each next value into the correct location among the earlier sorted values.',
    plain: 'Keep the left-hand cards ordered. Pick up the next card and hold it safely. Move larger cards right until there is a gap after a card no larger than the one you hold.',
    idea: 'The prefix is already sorted, so comparisons move backwards. Once a prefix value is no larger than the key, every earlier prefix value is also no larger.',
    vocabulary: [['Key', 'The saved value being inserted, not a permanent array index.'], ['Shift', 'Copy one prefix value to the next cell; it temporarily leaves duplicate cells.'], ['Gap', 'The cell at j + 1 where the held key will be placed.'], ['i', 'Original index of the next key.'], ['j', 'Backwards-moving index within the sorted prefix.']],
    invariant: 'Before outer iteration i, prefix 0..i-1 is sorted. The key remains saved while larger prefix values shift; after insertion prefix 0..i is sorted.',
    costs: [['Best', 'O(n)', 'Already sorted input makes one failed key comparison per insertion.'], ['Average / worst', 'O(n²)', 'Reverse input shifts across every earlier prefix cell.'], ['Auxiliary space', 'O(1) iterative; O(n) recursive', 'One saved key versus suspended recursive frames.'], ['Stable / in place / adaptive', 'Yes / yes / yes', 'Strict > never shifts an equal value past the key; few inversions mean few shifts.']],
    descending: 'Change arr[j] > key to arr[j] < key. Shift smaller prefix values right, stopping after a value at least as large as the key.',
    mistakes: [['Overwrite arr[i] without saving it', 'The key is lost during shifting.', 'Save int key = arr[i] first.'], ['Evaluate arr[j] before j >= 0', 'May read arr[-1] at the left edge.', 'Place the bounds condition first with &&.'], ['Insert at arr[j]', 'Writes before the identified gap.', 'Write arr[j + 1] = key.'], ['Describe every shift as a swap', 'Counts and intermediate states become wrong.', 'A shift performs one array write; a swap exchanges two values.']],
    use: 'A strong choice for small or nearly sorted arrays. It is simple, stable, and adaptive; it can also serve as the small-input stage of a larger sorting algorithm.',
  },
  merge: {
    summary: 'Split index ranges, finish both child calls, and merge their sorted results using protected temporary output.',
    definition: 'Merge sort is a divide-and-conquer comparison sort. It recursively sorts two disjoint halves and combines them by repeatedly selecting the smaller front value.',
    plain: 'One card needs no sorting. Sort small piles first, then combine two sorted piles by taking their smallest remaining front card. Repeat until the original range is complete.',
    idea: 'Splitting changes the problem boundaries, not the array values. Actual copying occurs during merging after both recursive child calls return.',
    vocabulary: [['start / end', 'Inclusive indexes bounding this call.'], ['mid', 'Last index of the left half; the right begins at mid + 1.'], ['Base case', 'start >= end: zero or one value.'], ['left / right', 'First unread indexes in each sorted run.'], ['out', 'Next free temp index, beginning at 0.'], ['Stable merge', 'Choose left on equality using <=.']],
    invariant: 'Before a merge, both input runs are sorted. During merging, temp contains the smallest consumed values in order, and each pointer identifies the next unread value in its run.',
    costs: [['Best / average / worst', 'O(n log n)', 'The standard implementation still splits and merges sorted input.'], ['Auxiliary arrays', 'O(n) peak', 'The largest merge needs n temporary cells.'], ['Call stack', 'O(log n)', 'Only one root-to-leaf path is active at once.'], ['Stable / in place / adaptive', 'Yes / no / no', 'Left-first ties preserve equals; the taught form allocates temp; no ordered-range shortcut.']],
    descending: 'Use arr[left] >= arr[right] to choose the left run. Both children must also be sorted descending; left-first equality still preserves stability.',
    mistakes: [['Right child starts at mid', 'Ranges overlap and may not shrink.', 'Use mid + 1.'], ['Merge before both calls return', 'Input runs are not yet known to be sorted.', 'Call left, call right, then merge.'], ['Ignore leftovers', 'Values vanish when one run becomes empty.', 'Copy the remaining suffix without key comparisons.'], ['Copy temp[k] to arr[k]', 'A nonzero-start merge overwrites the wrong range.', 'Write arr[start + k].'], ['Use < instead of <=', 'Equal right-run records can cross earlier left records.', 'Choose the left record on ties.']],
    use: 'Suitable for large unpredictable arrays when consistent O(n log n) time and stability matter and temporary memory is available.',
  },
};

function searchGuide(meta) {
  const kind = meta.kind, binary = kind === 'binary', input = binary ? BINARY_INPUT : LINEAR_INPUT;
  const run = search(kind, input, 18), frames = searchFrames(run);
  const intro = binary ? 'On a correctly sorted array, compare at the midpoint and discard the impossible half until the key is found or the range is empty.' : 'Check one position at a time and return the first matching index; report -1 only after every position has failed.';
  const cases = binary ? [
    ['Absent between values', input, 31, false], ['First value', input, 8, false], ['Duplicate key', [10, 20, 20, 20, 30], 20, false], ['Descending order', [...input].reverse(), 18, true], ['Empty and singleton', [18], 31, false],
  ] : [
    ['Absent key', input, 31, false], ['First match among duplicates', [7, 3, 7, 1], 7, false], ['Match at the last index', [9, 4, 2, 18], 18, false], ['Negative values', [-5, -2, 0, 8], -2, false], ['Empty and singleton', [18], 31, false],
  ];
  const worked = cases.map(([title, a, key, descending], i) => {
    const example = search(kind, a, key, descending), last = example.steps.at(-1);
    return `<article class="worked"><h3>${i + 1}. ${title}</h3><p>Input <code>[${a.join(', ')}]</code>; key <code>${key}</code>${descending ? '; descending comparisons' : ''}.</p>${figure(array(a, { active: last ? [last.i] : [], sorted: example.found >= 0 ? [example.found] : [] }), `Final probe/check at index ${last?.i ?? 'none'}; return ${example.found}.`)}${table(headersOfSearch(kind), rowsOfSearch(example))}<p class="result">Result ${example.found}; ${example.steps.length} ${binary ? 'midpoint probes' : 'key comparisons'}. ${i === 4 ? 'For [] the loop/body is never entered and -1 is returned with zero probes.' : ''}</p></article>`;
  }).join('');
  const recursive = binary ? figure(stack([{ name: 'binarySearchRec(0, 9)', next: 'Return the result from child range 0..3' }, { name: 'binarySearchRec(0, 3)', next: 'mid 1 matches 18: return 1' }]), 'The matching child returns 1; its parent forwards that result. Only one branch is called.') : figure(stack([{ name: 'linearSearchRec(index 0)', next: 'Return child result' }, { name: 'linearSearchRec(index 1)', next: 'Return child result' }, { name: 'linearSearchRec(index 2)', next: 'Check the current suffix' }]), 'Each failure suspends a parent and searches a smaller suffix. Ordinary Java does not eliminate this recursion stack.');
  return { ...meta, summary: intro, sections: [
    section('input', '1. Meet the array and the goal', `<p>An array stores values at zero-based indexes. A search key is the value you want; the answer is its position or a failure marker.</p>${figure(array(input), 'Index labels belong to positions, not to the values. Find key 18.')}<p>The last valid index is <code>${input.length - 1}</code>. Returning <code>18</code> would confuse a value with an index.</p>`),
    section('definition', '2. Definition and plain-language idea', `<p>${binary ? 'Binary search is a comparison search that repeatedly halves a sorted candidate range.' : 'Linear search, also called sequential search, compares each position with the key in order.'}</p>${figure(array(input, { active: binary ? [4] : [0], labels: binary ? { 0: 'low', 4: 'mid', 9: 'high' } : { 0: 'first check' } }), binary ? 'The first midpoint divides a sorted inclusive range into smaller candidates.' : 'Begin at index 0; all later positions remain possible until checked.')}<p>${intro}</p>${figure(binary ? array(input, { active: [1], discarded: [4, 5, 6, 7, 8, 9], labels: { 0: 'low', 1: 'next mid', 3: 'high' } }) : `<div class="pipeline"><div>Check index 0<br><code>63 == 18 → false</code></div><span>→</span><div>Check index 1<br><code>29 == 18 → false</code></div><span>→</span><div>Continue until<br><strong>match or end</strong></div></div>`, binary ? 'Since key 18 is smaller than 34, retain only indexes 0..3; the next midpoint is index 1.' : 'Each failed equality test advances exactly one index; the full array need not be sorted.')}${note(binary ? 'Precondition: ordering must match the comparison direction and searched field. Running this code on unsorted input can incorrectly report that a present key is absent.' : 'No sorted-order precondition. Equality provides no reason to skip distant positions.')}`),
    section('vocabulary', '3. Vocabulary before the trace', terms(binary ? [['Key', 'The target value.'], ['low / high', 'Inclusive candidate boundaries.'], ['mid', 'low + (high - low) / 2 with integer division.'], ['Probe', 'One visited midpoint; not necessarily one Java Boolean evaluation.'], ['Empty range', 'low > high.'], ['Invariant', 'If the key exists, a matching position remains within low..high.']] : [['Key', 'Target value, compared with arr[i].'], ['i', 'The current index, from 0 to length - 1.'], ['Match', 'arr[i] == key for primitive int values.'], ['Sentinel -1', 'Signals not found; it is never a valid array index.'], ['First occurrence', 'The earliest matching position because the scan returns immediately.']])) ,
    section('visual', '4. Visual trace: predict, then advance', `<p>Before pressing Next, say which position will be inspected and what the bounds/index will become. The marked row and picture share one selected step.</p>${player(`${kind}-main`, 'Search for 18', frames, ['Step', ...headersOfSearch(kind).slice(1)], rowsOfSearch(run).map((row) => row.slice(1)))}<p class="result">Return ${run.found} after ${run.steps.length} ${binary ? 'probes' : 'comparisons'}.</p>`),
    section('invariant', '5. Why the movement is valid', binary ? `<p>In ascending order, if arr[mid] is smaller than the key, every value to its left is also too small. Exclude the midpoint itself with <code>low = mid + 1</code>. The symmetric case uses <code>high = mid - 1</code>.</p>${figure(`<div class="pipeline"><div>Less than key<br><strong>discard</strong></div><span>→</span><div>mid checked<br><strong>exclude</strong></div><span>→</span><div>Possible larger values<br><strong>retain</strong></div></div>`, 'Each unsuccessful probe must strictly shrink the inclusive range.')}<p>A one-cell range still needs a comparison, so use <code>low &lt;= high</code>, not <code>low &lt; high</code>.</p>` : `<p>Before index i is checked, every position 0..i-1 has failed. After a failure, advance by exactly one position. On a match, the invariant proves this is the first match.</p>${figure(array([7, 3, 7, 1], { active: [0], sorted: [0], labels: { 0: 'return 0', 2: 'not visited' } }), 'Searching for 7 returns 0 even though index 2 also matches.')}`),
    section('implementation', '6. Fully commented Java implementation', `${code(JAVA[kind])}<h3>Build it from scratch</h3>${list(binary ? ['State the sorted-input precondition.', 'Initialize the inclusive range.', 'Repeat while a candidate remains.', 'Calculate the midpoint; test equality.', 'Exclude mid and the impossible side.', 'Return -1 after the range becomes empty.'] : ['Accept an array and key.', 'Visit every valid index from 0.', 'Return the matching index immediately.', 'Put return -1 after the loop.'])}`),
    section('recursive', '7. Recursive form and the call stack', `${code(JAVA[`${kind}Rec`])}${recursive}<p>${binary ? 'Initial call: binarySearchRec(arr, key, 0, arr.length - 1). Depth is O(log n) because each child retains at most about half the range.' : 'Initial call: linearSearchRec(arr, key, 0). Worst-case depth is O(n); the iterative version is preferable when that stack cost matters.'}</p>`),
    section('runnable', '8. Complete runnable program', `<p>Save as <code>${kind[0].toUpperCase() + kind.slice(1)}Demo.java</code>, compile with javac, then run the class name without an extension.</p>${code(runnable(kind, input, 18))}${code(String(run.found), 'Expected output')}`),
    section('examples', '9. Five worked cases and exact trace tables', worked),
    section('variations', '10. Variations: order, duplicates and reference values', binary ? `<p>For descending arrays, equality is unchanged. If key is larger than arr[mid], search LEFT by reducing high; otherwise search RIGHT by increasing low.</p><p>A standard binary search returns whichever equal midpoint it encounters first. To find the first duplicate, record the match and continue left instead of returning immediately.</p>${figure(array([10, 20, 20, 20, 30], { active: [2], sorted: [2], labels: { 2: 'first midpoint' } }), 'Searching for 20 returns index 2, even though the first occurrence is index 1.')}` : `<p>To find the last occurrence, continue scanning and retain the latest matching index. To count matches, increment a counter instead of returning. Descending, ascending and unsorted arrays all use the same equality scan.</p>${code(JAVA.strings)}<p>Objects need a field comparison or an appropriate equals method. Guard nullable references before invoking a method.</p>`),
    section('properties', '11. Properties and why the cost occurs', `${table(['Property', 'Result', 'Reason'], binary ? [['Best time', 'O(1)', 'First midpoint is a match.'], ['Average / worst', 'O(log n)', 'Every failed probe removes approximately half the candidates.'], ['Extra space', 'O(1) iterative; O(log n) recursive', 'Bounds versus suspended frames.'], ['Input order', 'Required', 'Discard decisions depend on order.'], ['Duplicates', 'Any matching midpoint', 'No first/last guarantee.'], ['Input mutated?', 'No', 'Only bounds change.']] : [['Best time', 'O(1)', 'First position matches.'], ['Average / worst', 'O(n)', 'Number of visited positions grows with input length.'], ['Extra space', 'O(1) iterative; O(n) recursive', 'Index versus suspended frames.'], ['Input order', 'Not required', 'Checks use equality only.'], ['Duplicates', 'First match', 'Immediate return.'], ['Input mutated?', 'No', 'The method only reads cells.']])}${levels(kind)}<p>${binary ? 'A successful or unsuccessful midpoint visit is counted as one probe in these tables. The exact Java code can evaluate equality and then a direction comparison on a failed probe; do not call probe count the exact number of all Boolean expressions.' : 'The tables count one primitive-key equality test per visited cell. Boundary/loop conditions are not included.'}</p>`),
    section('when', '12. When to choose this method', `<p>${binary ? 'Choose binary search for repeated lookups on data already sorted by the relevant key. Sorting solely for one lookup may cost more than a linear scan. Binary search also relies on efficient random access; a linked list does not provide array-like midpoint access.' : 'Choose linear search for small, unsorted, or one-off searches. It avoids sorting cost and works with sequential access structures.'}</p>`),
    section('errors', '13. Common mistakes and repairs', table(['Mistake', 'Consequence', 'Repair'], binary ? [['Search an unsorted array', 'Can discard a present match.', 'Sort by the same searched key/direction first.'], ['Use mid instead of mid + 1 or mid - 1', 'Range may stop shrinking.', 'Exclude the already-tested midpoint.'], ['Use low < high', 'Misses a final single candidate.', 'Use low <= high.'], ['Return a value instead of index', 'Wrong output contract.', 'Return mid.'], ['Assume first duplicate', 'Standard search can return a later occurrence.', 'Continue left after recording a match.']] : [['Use i <= arr.length', 'Reads one cell beyond the array.', 'Use i < arr.length.'], ['Return -1 inside the loop after first failure', 'Stops before later matches.', 'Return failure after the loop.'], ['Return arr[i]', 'Returns a value rather than position.', 'Return i.'], ['Use == for String text', 'Compares references.', 'Use a null-safe equals test.']])) ,
    section('practice', '14. Exam-style practice with explanations', `${question('A. Trace key 31 on the main input. Show every index/bound and the failure result. [6]', `${table(headersOfSearch(kind), rowsOfSearch(search(kind, input, 31)))}<p>Every retained candidate is eliminated; return -1. ${binary ? 'Four midpoint probes are required.' : 'Ten equality checks are required.'}</p>`)}${question('B. Explain the best and worst time using input examples. [4]', `<p>${binary ? 'Best: key equals the first midpoint, one probe. Worst: key absent or only located after the range repeatedly halves, logarithmic probes.' : 'Best: key at index 0, one equality test. Worst: key last or absent, n equality tests.'}</p>`)}${question('C. Debug the bounds and return statement. [4]', `<p>${binary ? 'low and high are inclusive. Use low <= high, calculate the overflow-safe midpoint, and exclude mid using ±1. The not-found return belongs after the range empties.' : 'i must stay below length; a failed equality test means continue, not return -1. Failure belongs after the loop.'}</p>`)}${question('D. Return the first occurrence of a duplicate. What must change? [3]', `<p>${binary ? 'Keep a result variable. On equality record mid, set high = mid - 1, and continue. Return the recorded index after the loop.' : 'Nothing: the left-to-right immediate return already selects the first occurrence.'}</p>`)}${question('E. Empty array: can this code access index 0? [2]', `<p>No. ${binary ? 'high is -1, so low <= high is false.' : 'i = 0 is not less than length = 0.'} It returns -1 without reading a cell.</p>`)}`),
    section('summary', '15. Test-ready summary and mastery check', `<p class="summary">${intro}</p>${list(binary ? ['State the sorted-order precondition.', 'Show low, high, mid and evaluated conditions on each probe.', 'Shrink the range with mid ± 1.', 'Separate probe counts from all Java comparison evaluations.', 'Distinguish iterative space from recursive stack space.'] : ['Return an index, or -1 after the full scan.', 'Keep every index in 0..length-1.', 'Know why unsorted input is acceptable.', 'Explain first-match behavior.', 'Use equals for reference text.'])}`),
  ] };
}

function sortGuide(meta) {
  const kind = meta.kind, info = SORT_INFO[kind], input = kind === 'merge' ? MERGE_INPUT : SORT_INPUT, run = sort(kind, input);
  const mainFrames = run.steps.map((step, i) => ({ title: step.title, visual: kind === 'merge' ? figure(`${recursionTree(input, step.range)}${array(step.a)}${stack(step.stack)}`, 'Original values label the leaves; the array underneath shows the current shared storage. Only the active root-to-leaf path occupies the stack.') : figure(`${step.key !== undefined ? `<div class="held-key">Held key: <strong>${step.key}</strong></div>` : ''}${array(step.a, { active: step.active, sorted: step.sorted || [] })}`, 'Indexes remain fixed. Highlighted cells are the current comparison or write; green prefix/suffix is known sorted.'), explanation: step.explanation, print: kind === 'merge' ? false : Boolean(step.print || kind === 'bubble' && (i === run.steps.length - 1 || run.steps[i + 1]?.pass !== step.pass)) }));
  const mainRows = run.steps.map((step) => [step.title, step.explanation, `[${step.a.join(', ')}]`]);
  const compact = kind === 'merge' ? table(['Return', 'Call # / merge bounds', 'Left sorted run', 'Right sorted run', 'Merged result', 'Key comparisons'], run.returns.map((r) => [r.number, `${r.call} / (${r.lo}, ${r.mid}, ${r.hi})`, `[${r.left}]`, `[${r.right}]`, `[${r.result}]`, r.comparisons])) : table(['Pass', 'Array before', 'Evaluated comparisons / decisions', 'Array after', 'Key comparisons', kind === 'insertion' ? 'Shifts' : 'Swaps'], run.passes.map((p) => [p.number, `[${p.before}]`, p.operations.join('; '), `[${p.after}]`, p.comparisons, p.moves]));
  const cases = [['Nearly sorted', [1, 2, 4, 3, 5]], ['Reverse order', [5, 4, 3, 2, 1]], ['Duplicate values', [2, 2, 1, 3]], ['Uneven length', [38, 27, 43, 3, 9]], ['Descending target', [8, 3, 5, 1]]];
  const worked = cases.map(([title, a], i) => {
    const desc = i === 4, example = sort(kind, a, desc);
    const rows = kind === 'merge' ? example.returns.map((r) => [r.number, `${r.lo}..${r.hi}`, `[${r.left}] + [${r.right}]`, `[${r.result}]`, r.comparisons]) : example.passes.map((p) => [p.number, `[${p.before}]`, p.operations.join('; '), `[${p.after}]`, p.comparisons]);
    return `<article class="worked"><h3>${i + 1}. ${title}</h3>${figure(`${array(a)}<p class="arrow">↓ ${desc ? 'descending' : 'ascending'} ${meta.title.toLowerCase()}</p>${array(example.result, { sorted: allSorted(example.result) })}`, 'The trace below connects the input diagram to the final result.')}${table(kind === 'merge' ? ['Return', 'Range', 'Inputs', 'Result', 'Key comparisons'] : ['Pass', 'Before', 'Evaluated conditions', 'After', 'Key comparisons'], rows)}<p class="result">${example.comparisons} key comparisons; ${kind === 'merge' ? `${example.writes} copy-back writes` : `${example.moves} ${kind === 'insertion' ? 'shifts' : 'swaps'}`}. ${desc ? info.descending : ''}</p></article>`;
  }).join('');
  let mechanics = '';
  if (kind === 'merge') {
    const final = run.returns.at(-1), micro = final.micro;
    const frames = micro.map((s, i) => ({ title: s.title, visual: figure(`<h4>Left run ${s.lo}..${s.mid}; left = ${s.lo + s.i}</h4>${array(s.left, { offset: s.lo, active: s.i < s.left.length ? [s.i] : [], discarded: s.left.flatMap((_, j) => j < s.i ? [j] : []), labels: s.i < s.left.length ? { [s.i]: 'left' } : {} })}<h4>Right run ${s.mid + 1}..${s.hi}; right = ${s.mid + 1 + s.j}</h4>${array(s.right, { offset: s.mid + 1, active: s.j < s.right.length ? [s.j] : [], discarded: s.right.flatMap((_, j) => j < s.j ? [j] : []), labels: s.j < s.right.length ? { [s.j]: 'right' } : {} })}<h4>Temporary output; out = ${s.out}</h4>${array([...s.temp, ...Array(s.hi - s.lo + 1 - s.temp.length).fill(null)], { sorted: s.temp.map((_, j) => j) })}${s.phase === 'copyback' ? `<h4>Shared array during copy-back</h4>${array(s.a)}` : ''}`, 'Crossed values have been consumed; pointers may reach one-past-the-run-end without being dereferenced. Temporary output indexes begin at 0.'), explanation: s.explanation, print: [0, 2, 5, 8, micro.length - 1].includes(i) }));
    mechanics = `<p>The completed-return view answers <em>which merge returns next?</em> This view answers <em>how does a merge construct its result?</em></p>${player('merge-pointers', 'The final merge: every selection, leftover and copy-back', frames, ['Step', 'left (absolute)', 'right (absolute)', 'out', 'Operation', 'temp'], micro.map((s) => [s.lo + s.i, s.mid + 1 + s.j, s.out, s.explanation, `[${s.temp}]`]))}<p class="result">Final merge: 5 key comparisons, 3 leftover copies, 8 temp writes, then 8 copy-back writes. Loop-bound checks are not counted as key comparisons.</p>${note('The temporary cells protect every unread value. The output offset start + k is essential when merging a subrange that does not begin at 0.')}`;
  } else if (kind === 'insertion') {
    const p = run.passes[2];
    mechanics = `<p>Pass 3 saves key 1 before shifting [2, 4, 5]. The temporary duplicates in the array are expected; the held key is the missing value.</p>${figure(`<div class="held-key">Held key <strong>1</strong></div>${array([2, 4, 5, 5, 3], { active: [2, 3], labels: { 3: '5 copied' } })}<p class="arrow">↓ shift 4, then 2</p>${array(p.after, { sorted: [0, 1, 2, 3], labels: { 0: 'key inserted' } })}`, 'A shift writes one array cell; the final insertion is another array write. Six shifts plus four insertions gives ten array writes on the main input.')}`;
  } else if (kind === 'selection') {
    mechanics = `${figure(`${array(['2a', '2b', '1'])}<p class="arrow">↓ swap indexes 0 and 2</p>${array(['1', '2b', '2a'], { sorted: [0], active: [2] })}`, 'Equal keys 2a and 2b reverse relative order. Ordinary swapping selection sort is not stable.')}<p>The tags distinguish records whose comparison key is the same. A stable algorithm must preserve those tags in their original order.</p>`;
  } else {
    mechanics = `${figure(`${array([4, 2, 5, 1, 3], { active: [0, 1] })}<p class="arrow">↓ compare 4 &gt; 2, swap</p>${array([2, 4, 5, 1, 3], { active: [1, 2] })}<p class="arrow">↓ continue scanning; 5 finally reaches the end</p>${array(run.passes[0].after, { sorted: [4], labels: { 4: 'locked' } })}`, 'One swap uses two writes to input-array cells; the temporary variable assignment is not an array write.')}<p>One non-swap does not prove the whole array is sorted. Only a full no-swap pass supports the early stop.</p>`;
  }
  const recursive = kind === 'merge' ? `<p>The primary implementation is already recursive. Its 15 calls form a tree, but Java executes them depth-first and retains only a path on the stack.</p>${figure(recursionTree(input), 'Eight leaves, seven internal merge nodes, fifteen calls. Splitting leaves the original array unchanged.')}<h3>The live stack at the first base case</h3>${figure(stack(run.steps.find((step) => step.title.startsWith('Call 4:')).stack), 'Only four frames are live at this moment: root, left half, left pair and first leaf. The other eleven tree nodes are not simultaneous stack frames.')}<p>The base-case frame returns and disappears. Its parent then calls the right leaf, merges the pair, and returns to its own parent. A parent resumes exactly where its child call suspended it.</p><h3>Every call, with its midpoint</h3>${table(['Call #', 'Depth', 'Range', 'mid', 'Next work'], run.calls.map((c) => [c.call, c.depth, `${c.lo}..${c.hi}`, c.mid ?? '-', c.lo === c.hi ? 'Base case: return' : `left ${c.lo}..${c.mid}, right ${c.mid + 1}..${c.hi}, then merge`]))}<p>For 0..3, calls visit 0..1 and its leaves, then merge 0..1, then visit 2..3 and its leaves, then merge 2..3, then merge 0..3. Merges are NOT executed level by level.</p>` : `${code(JAVA[`${kind}Rec`])}${figure(stack(kind === 'insertion' ? [{ name: 'insertionSortRec(n=5)', next: 'Insert 3 after child returns' }, { name: 'insertionSortRec(n=4)', next: 'Insert 1 after child returns' }, { name: 'insertionSortRec(n=3)', next: 'Insert 5 after child returns' }, { name: 'insertionSortRec(n=2)', next: 'Insert 2 after child returns' }, { name: 'insertionSortRec(n=1)', next: 'Base case returns immediately' }] : kind === 'bubble' ? [{ name: 'bubbleSortRec(n=5)', next: 'Child sorts remaining prefix 0..3' }, { name: 'bubbleSortRec(n=4)', next: 'Pass fixes the largest remaining value at index 3' }] : [{ name: 'selectionSortRec(i=0)', next: 'Child fills remaining positions 1..4' }, { name: 'selectionSortRec(i=1)', next: 'Scan suffix 1..4 and fill index 1' }]), kind === 'insertion' ? 'Calls descend to n=1; insertions execute as n=2,3,4,5 return. The arrays after each return match the pass table.' : 'Unlike iterative auxiliary space, suspended recursive frames require O(n) stack space in the worst case.')}`;
  return { ...meta, summary: info.summary, sections: [
    section('input', '1. The array we will sort', `<p>Arrays use zero-based positions. Sorting changes which values occupy those positions. The target is ascending order; record tags would move with their values.</p>${figure(array(input), `Initial input [${input}]. ${kind === 'merge' ? 'Inclusive range 0..7.' : 'Five fixed index positions 0..4.'}`)}<p>We will distinguish comparisons, swaps, shifts, temporary writes and copy-back writes. They are different units.</p>`),
    section('definition', '2. Definition and plain language', `<p>${info.definition}</p>${kind === 'merge' ? figure(recursionTree(input), 'Divide the original problem into disjoint index ranges. One-value leaves are the base cases.') : figure(`<div class="pipeline"><div>${kind === 'bubble' ? 'Compare neighbours' : kind === 'selection' ? 'Scan the whole suffix' : 'Save the next key'}</div><span>→</span><div>${kind === 'bubble' ? 'Swap if inverted' : kind === 'selection' ? 'Remember best index' : 'Shift larger prefix values'}</div><span>→</span><div>${kind === 'bubble' ? 'Lock a rightmost value' : kind === 'selection' ? 'Fill next final position' : 'Insert into the gap'}</div></div>`, 'The algorithm has a distinct decision and movement rule; each completed pass grows its known-sorted region.')}<p>${info.plain}</p>${kind === 'merge' ? figure(`<h4>Two sorted piles</h4>${array([29, 63], { labels: { 0: 'left front' } })}${array([72, 85], { labels: { 0: 'right front' } })}<p class="arrow">↓ take the smaller front, then advance only that pile</p>${array([29, 63, 72, 85], { sorted: [0, 1, 2, 3] })}`, 'Merge works because both input runs are already sorted.') : figure(`${kind === 'insertion' ? '<div class="held-key">Hold key <strong>2</strong></div>' : ''}${array(input, { active: kind === 'selection' ? [0, 3] : [0, 1], labels: kind === 'selection' ? { 0: 'fill here', 3: 'minimum' } : {} })}<p class="arrow">↓ ${kind === 'bubble' ? 'finish the neighbouring comparisons' : kind === 'selection' ? 'swap the selected minimum into index 0' : 'shift 4 right and insert 2'}</p>${array(run.passes[0].after, { sorted: kind === 'bubble' ? [4] : kind === 'selection' ? [0] : [0, 1] })}`, 'A concrete first pass: highlighted positions explain the choice; the green region records the completed result.')}${note(info.idea)}`),
    section('vocabulary', '3. Vocabulary and the central invariant', `${terms(info.vocabulary)}<p><strong>Invariant:</strong> ${info.invariant}</p>`),
    section('visual', '4. Step through the complete execution', `<p>Predict the next decision before advancing. Next updates both the scene and the visibly marked trace row. Print includes the completed states and full table.</p>${player(`${kind}-main`, kind === 'merge' ? 'Depth-first calls and merge returns' : 'One comparison or write at a time', mainFrames, ['Step', 'Operation', 'Reason', 'Shared array'], mainRows)}<p class="result">Final result: [${run.result.join(', ')}].</p>`),
    section('trace', '5. Exam-style completed-pass / return table', `<p>${kind === 'merge' ? 'One row per completed merge, in return order. Each row identifies its actual call and ranges.' : 'One row per outer-loop pass. These are the completed states to reproduce when an exam asks for the array after each pass.'}</p>${compact}`),
    section('mechanics', '6. What actually moves, and why', mechanics),
    section('implementation', '7. Fully commented Java implementation', `${code(JAVA[kind])}<h3>Write it from scratch</h3>${list(kind === 'merge' ? ['State the inclusive base case.', 'Calculate a midpoint that shrinks both ranges.', 'Sort left, sort right, then merge.', 'Track both input pointers and temp output.', 'Choose one front value; advance only its source.', 'Copy both possible leftover suffixes.', 'Copy temp back with start + k.'] : kind === 'insertion' ? ['Start at the second value.', 'Save the key.', 'Walk backwards through the sorted prefix.', 'Shift strictly larger values right.', 'Insert into j + 1.'] : kind === 'selection' ? ['Choose the next final position.', 'Initialize the minimum index to it.', 'Scan the complete suffix.', 'Remember better candidate indexes.', 'Perform at most one final swap.'] : ['Start a new pass and reset swapped.', 'Compare neighbours within the active prefix.', 'Swap strictly inverted pairs.', 'Shorten the next pass by one fixed position.', 'Stop after a whole no-swap pass.'])}`),
    section('recursive', '8. Recursion, calls and returns', recursive),
    section('runnable', '9. Complete runnable program', `<p>Save as <code>${kind[0].toUpperCase() + kind.slice(1)}Demo.java</code>. The code includes the method(s) and a main entry point.</p>${code(runnable(kind, input))}${code(`[${run.result.join(', ')}]`, 'Expected console output')}`),
    section('descending', '10. Descending order: change the decision', `<p>${info.descending}</p>${note('Keep the bounds and movement rules consistent. Reversing a final array is a different procedure and does not reproduce the descending trace of this implementation.')}`),
    section('examples', '11. Five worked examples', `<p>Each case has input and result diagrams, evaluated decisions or merge inputs, exact counts, and a final state.</p>${worked}`),
    section('properties', '12. Properties and why the complexity occurs', `${table(['Property', 'Result', 'Reason'], info.costs)}${levels(kind)}<p>${kind === 'merge' ? 'For n=8, three merge levels each copy eight values, so this execution has 24 copy-back writes and 24 writes into temporary output. This is work across levels, not 24 simultaneous temporary cells: peak auxiliary storage remains O(n). The active call path has O(log n) frames.' : kind === 'selection' ? 'For n=5, the full suffix scans make 4+3+2+1=10 key comparisons even on sorted input. Fewer swaps do not imply fewer comparisons.' : kind === 'insertion' ? 'On the main input there are 8 key comparisons, 6 shifts and 4 insertion writes. The guard j >= 0 is not a key comparison. Reverse input gives the triangular worst-case number of shifts; sorted input makes n-1 failed key comparisons.' : 'On the main input there are 10 key comparisons and 6 swaps. A swap writes two input cells, giving 12 array writes. A no-swap first pass on a sorted five-value array uses only 4 comparisons.'}</p>`),
    section('when', '13. When to choose it', `<p>${info.use}</p>`),
    section('errors', '14. Common mistakes, symptoms and repairs', table(['Attempt', 'What goes wrong', 'Repair'], info.mistakes)),
    section('practice', '15. Exam-style practice and worked answers', `${question('A. Trace [8, 3, 5, 1] in descending order. Show every completed pass/merge. [8]', (() => { const e = sort(kind, [8, 3, 5, 1], true); return `${table(kind === 'merge' ? ['Return', 'Left', 'Right', 'Result'] : ['Pass', 'Before', 'After', 'Key comparisons'], kind === 'merge' ? e.returns.map((r) => [r.number, `[${r.left}]`, `[${r.right}]`, `[${r.result}]`]) : e.passes.map((p) => [p.number, `[${p.before}]`, `[${p.after}]`, p.comparisons]))}<p>Final result [${e.result}]. ${info.descending}</p>`; })())}${question('B. Explain stability with tagged equal keys. [4]', `<p>${kind === 'selection' ? 'Swap 1 with 2a in [2a, 2b, 1]: result [1, 2b, 2a]. The equal records crossed, so the taught version is not stable.' : kind === 'merge' ? 'On a tie between a left 2a and right 2b, <= selects 2a. Repeated left-first choices preserve original order.' : 'Strict inversion comparisons do not move a value past an equal one. Using >= (or <= descending) would remove that guarantee.'}</p>`)}${question('C. Give the time and space, then justify both. [5]', `<p>${info.costs.map(([name, result, reason]) => `${name}: ${result}. ${reason}`).join(' ')}</p>`)}${question('D. Debug the code before tracing it. [4]', `${table(['Mistake', 'Symptom', 'Fix'], info.mistakes.slice(0, 2))}`)}${question('E. What happens for [] and [7]? [2]', '<p>Both are already sorted. No key comparisons or value movements are required. Merge sort returns at its base case; the iterative methods never enter a pass.</p>')}${kind === 'merge' ? question('F. Merge [2, 9] and [4, 5, 8]. Show pointers and leftovers. [6]', '<p>Choose 2 (left), 4 (right), 5 (right), 8 (right), then copy leftover 9. Four key comparisons, one leftover, five output writes. Relative pointers end at i=2,j=3; result [2,4,5,8,9].</p>') : ''}`),
    section('summary', '16. Test-ready summary and mastery check', `<p class="summary">${info.summary}</p>${list(['I can introduce every variable before using it.', 'I can draw the current array with index labels.', 'I can evaluate conditions with the actual values.', 'I can distinguish pass summaries from individual operations.', 'I can trace descending and duplicate cases.', 'I can justify stability, time and auxiliary space.', 'I can test empty, singleton, sorted and reverse input.'])}`),
  ] };
}

const folderDiagram = () => figure(`<div class="folder-grid"><div><h4>Source root: src/</h4><pre>src/\n  pkg/\n    A.java\n    B.java\n    Tester.java\n  app/\n    Main.java</pre></div><div><h4>Output / classpath root: classes/</h4><pre>classes/\n  pkg/\n    A.class\n    B.class\n    Tester.class\n  app/\n    Main.class</pre></div></div>`, 'Package identity is below each root. src and classes are roots, not parts of the package name.');
const identityDiagram = () => figure(`<div class="pipeline"><div><small>Declaration</small><code>package pkg;</code></div><span>→</span><div><small>Source path</small><code>src/pkg/A.java</code></div><span>→</span><div><small>Class identity</small><code>pkg.A</code></div></div>`, 'Dots in a package name correspond to directories below a source/classpath root.');
const buildDiagram = () => figure(`<div class="pipeline"><div><small>javac reads</small><code>src/pkg/Tester.java</code></div><span>→</span><div><small>-d classes writes</small><code>classes/pkg/Tester.class</code></div><span>→</span><div><small>java resolves</small><code>classes + pkg.Tester</code></div></div>`, 'Runtime lookup combines the classpath root with the fully qualified binary name, then invokes main.');
const command = `# Run from the project folder that contains src and classes.
javac -d classes -sourcepath src src/pkg/A.java src/pkg/B.java src/pkg/Tester.java src/app/Main.java

# Classpath points to the ROOT above pkg and app, not to classes/pkg.
java -classpath classes pkg.Tester
java -classpath classes app.Main`;
function packageGuide(meta) {
  const kind = meta.kind;
  const summary = kind === 'imports' ? 'An import lets a source file use a simple type name; package declarations supply identity, and access modifiers supply visibility.' : kind === 'package' ? 'Declare a package, match its path below the source root, and coordinate the class name, public visibility and entry point.' : 'Compile source into package directories, then run the fully qualified class from the correct classpath root.';
  const frames = [
    { title: '1. Declare identity', visual: identityDiagram(), explanation: 'package pkg makes the public class A identifiable as pkg.A. The file belongs below source root src in pkg/A.java.', print: true },
    { title: '2. Compile source', visual: folderDiagram(), explanation: 'javac -d classes writes compiled output below classes, preserving package folders. -sourcepath src locates source dependencies.', print: false },
    { title: '3. Resolve and run', visual: buildDiagram(), explanation: 'java -classpath classes pkg.Tester locates classes/pkg/Tester.class and invokes its main method.', print: true },
  ];
  const errors = [['cannot find symbol: Scanner', 'Simple name is not in scope.', 'Add import java.util.Scanner or use the fully qualified name.'], ['reference to Date is ambiguous', 'Two wildcard-imported packages contain Date.', 'Use a specific import or fully qualified name.'], ['package pkg does not exist', 'Compiler cannot locate sources/compiled dependencies.', 'Use -sourcepath src or -classpath classes as appropriate.'], ['class A is public, should be declared in A.java', 'Public class and filename disagree.', 'Use A.java with public class A.'], ['Could not find or load main class pkg.Tester', 'Wrong classpath root/name or missing compiled file.', 'Use classes as root and pkg.Tester without .class.'], ['Main method not found in class pkg.A', 'That helper is not an entry-point class.', 'Run pkg.Tester or app.Main.'], ['secret() is not public in B', 'Cross-package access to a package-private member.', 'Use a public API; an import cannot grant visibility.']];
  const topicBody = kind === 'imports' ? `${terms([['Package', 'A namespace grouping related top-level types.'], ['Import', 'A source-level name-shortening declaration.'], ['Fully qualified name', 'Package plus type, such as java.util.Scanner.'], ['Wildcard', 'Imports accessible types directly in that package; not its subpackages.'], ['java.lang', 'Automatically imported; contains String, System and Math.']])}${figure('<div class="qualified-name"><span>java.util<br><small>package</small></span><b>.</b><span>Scanner<br><small>class</small></span></div>', 'The package prefix identifies the class; the import permits the shorter spelling Scanner.')}<p>An import does not install a library, execute code or copy a class. A dependency still has to be available to compilation and runtime.</p>${table(['Package', 'Purpose', 'Examples'], [['java.lang', 'Core language types, automatic import', 'String, System, Math'], ['java.util', 'Utilities and collections', 'Scanner, Arrays, ArrayList'], ['java.io', 'File and stream I/O', 'File, BufferedReader, PrintWriter']])}` : kind === 'package' ? `${terms([['Source root', 'Directory above the first package segment.'], ['package pkg;', 'Defines membership; first non-comment statement.'], ['public class A', 'Externally visible class saved as A.java.'], ['Package-private', 'No access modifier; visible within the same package.'], ['Entry point', 'public static void main(String[] args).']])}${identityDiagram()}${folderDiagram()}` : `${terms([['javac', 'Java compiler: source .java to compiled .class.'], ['-sourcepath src', 'Where to find source dependencies.'], ['-d classes', 'Where to write compiled package directories.'], ['-classpath classes', 'Where Java begins lookup of compiled classes.'], ['Fully qualified name', 'pkg.Tester, not a slash path and not a filename.']])}${buildDiagram()}${folderDiagram()}`;
  const companionProject = `${code(JAVA.packageA)}${code(JAVA.packageB)}${code(JAVA.packageTester)}${code(JAVA.packageMain)}${code(command, 'Commands')}`;
  const focusedCode = kind === 'imports' ? `${code(JAVA.imports)}<p>Input 5 prints [1, 2, 5] after sorting. Save at src/app/ImportDemo.java.</p>${code('javac -d classes src/app/ImportDemo.java\njava -classpath classes app.ImportDemo', 'Commands')}<h3>Complete companion project for the package workflow</h3><p>The following four source files make the earlier diagram and the later output/practice tables reproducible within this guide. Their package declarations and paths are explicit.</p>${companionProject}` : companionProject;
  const examples = kind === 'imports' ? [
    ['Specific import', 'import java.util.Scanner;', 'Scanner in = new Scanner(System.in);', 'The single imported type is available by its simple name.'],
    ['Fully qualified alternative', 'No Scanner import', 'java.util.Scanner in = new java.util.Scanner(System.in);', 'Same type; longer spelling resolves its identity directly.'],
    ['Wildcard boundary', 'import java.util.*;', 'Scanner works; a subpackage class still needs its own import.', 'Wildcard imports do not recurse into subpackages.'],
    ['Automatic names', 'No import java.lang.String;', 'String message = "Hello";', 'java.lang types are automatically imported.'],
    ['Ambiguous simple name', 'import java.util.*; import java.sql.*;', 'java.util.Date chosen = new java.util.Date();', 'Both packages define Date; qualify the required type.'],
  ] : [
    ['One-level package', 'package pkg; public class A', 'src/pkg/A.java → classes/pkg/A.class', 'Identity is pkg.A.'],
    ['Nested package', 'package ub.cs.tools; public class Helper', 'src/ub/cs/tools/Helper.java → classes/ub/cs/tools/Helper.class', 'Identity is ub.cs.tools.Helper; roots are excluded.'],
    ['Same-package call', 'pkg.Tester calls B.secret()', 'No import; package-private access allowed.', 'Both classes belong to pkg.'],
    ['Cross-package call', 'app.Main imports pkg.B', 'B.twice(5) → 10; B.secret() is inaccessible.', 'Import shortens the class name but does not grant member access.'],
    ['Runtime root', 'java -classpath classes app.Main', 'classes/app/Main.class → main → output', 'The root is classes, not classes/app.'],
  ];
  const exampleHtml = examples.map(([title, input, resolution, reason], i) => `<article class="worked"><h3>${i + 1}. ${title}</h3>${figure(`<div class="pipeline"><div><small>Given</small><code>${escape(input)}</code></div><span>→</span><div><small>Resolution / result</small><code>${escape(resolution)}</code></div></div>`, reason)}${table(['Step', 'Evidence', 'Conclusion'], [[1, input, 'Identify package/type/root'], [2, resolution, reason]])}</article>`).join('');
  const definition = kind === 'imports' ? 'A Java package supplies a namespace for types. An import declaration lets a compilation unit refer to an accessible type using its simple name instead of its fully qualified name.' : kind === 'package' ? 'A user-defined package groups named types under a declared namespace. The package declaration, source location below the root, and dotted class identity must agree.' : 'Compilation translates Java source into class files. Running a packaged class combines a classpath root with a fully qualified class name and invokes its main method.';
  const definitionVisual = kind === 'imports' ? figure('<div class="pipeline"><div><small>Fully qualified type</small><code>java.util.Scanner</code></div><span>→</span><div><small>Import declaration</small><code>import java.util.Scanner;</code></div><span>→</span><div><small>Simple spelling</small><code>Scanner</code></div></div>', 'Import changes which spelling is available in this source file; all three boxes refer to the same type.') : kind === 'package' ? identityDiagram() : buildDiagram();
  return { ...meta, summary, sections: [
    section('goal', '1. The problem and the plain-language idea', `<p>${summary}</p>${definitionVisual}<p>Think of a package as a class address. Two classes may share a simple name when their package addresses differ. Source paths and compiled paths are measured from different roots.</p>${folderDiagram()}`),
    section('definition', '2. Definition and essential vocabulary', `<p>${definition}</p>${definitionVisual}${topicBody}`),
    section('workflow', '3. Visual workflow: declare, compile, run', `${player(`packages-${kind}`, 'Follow the same class through three representations', frames, ['Step', 'Stage', 'Input', 'Output / resolution'], [['Declare', 'package pkg; / src/pkg/A.java', 'pkg.A'], ['Compile', 'javac -d classes -sourcepath src ...', 'classes/pkg/*.class'], ['Run', 'java -classpath classes pkg.Tester', 'classes/pkg/Tester.class → main']])}`),
    section('rules', '4. Rules before code', `${list(['Put a package declaration before import declarations and the class declaration.', 'Match the package path below the source root.', 'Match a public class name to its source filename, including case.', 'Classes in the same package do not need imports for one another.', 'Named packages cannot import a class from the unnamed default package.', 'An import does not change an access modifier.', 'Use a fully qualified class name when launching a packaged program.'])}${table(['Representation', 'Example', 'Root'], [['Package', 'pkg', 'Not a filesystem root'], ['Source', 'src/pkg/A.java', 'src'], ['Compiled', 'classes/pkg/A.class', 'classes'], ['Binary name', 'pkg.A', 'Root supplied separately by classpath']])}`),
    section('implementation', '5. Fully commented Java and commands', focusedCode),
    section('visibility', '6. Visibility: imports and access are different', `${table(['Member modifier', 'Same class', 'Same package', 'Subclass outside package', 'Unrelated outside class'], [['public', 'Yes', 'Yes', 'Yes', 'Yes'], ['protected', 'Yes', 'Yes', 'Yes, with subclass access restrictions', 'No'], ['none (package-private)', 'Yes', 'Yes', 'No', 'No'], ['private', 'Yes', 'No', 'No', 'No']])}<p>Protected access from a different package is through inheritance and is subject to receiver restrictions; it is not blanket permission to access any superclass object. A top-level class may be public or package-private, not protected/private.</p>${code('import pkg.B;\n// Legal in app.Main: B.twice(5)\n// Illegal in app.Main: B.secret()\n// Importing B does not alter secret() visibility.', 'Access comparison')}`),
    section('trace', '7. Source-to-output trace table', `${table(['Stage', 'Given', 'Resolution', 'Result'], [['Declare', 'package pkg; / Tester.java', 'pkg.Tester', 'src/pkg/Tester.java'], ['Compile', 'javac -d classes -sourcepath src ...', 'Write below output root', 'classes/pkg/Tester.class'], ['Run', 'java -classpath classes pkg.Tester', 'Find class and invoke main', 'Hello from pkg.A / 42 / pkg only'], ['Cross-package', 'java -classpath classes app.Main', 'Public APIs of pkg.A and pkg.B', 'Hello from pkg.A / 10']])}${code('Hello from pkg.A\n42\npkg only', 'pkg.Tester output')}${code('Hello from pkg.A\n10', 'app.Main output')}`),
    section('examples', '8. Five worked cases', exampleHtml),
    section('scratch', '9. Build or explain it from scratch', `${list(kind === 'imports' ? ['Identify the package and class you need.', 'Decide specific import or fully qualified spelling.', 'Keep package first, imports second, class third.', 'Check that the imported type and used members are accessible.', 'Compile a valid example; distinguish naming errors from visibility errors.'] : ['Choose the package and public class names.', 'Create matching source directories.', 'Write the package declaration first.', 'Add a main entry point to the class you intend to run.', 'Compile with an output root and source dependency root.', 'Run with a classpath root and fully qualified name.', 'Check output and exercise cross-package public access.'])}`),
    section('properties', '10. Properties and when to use packages', `<p>Packages organize names and collaboration; imports are compile-time name resolution conveniences. A wildcard is not a performance optimization. There is no useful sorting-style O(n) claim to assign to an import declaration.</p>${table(['Property', 'Practical consequence'], [['Namespace', 'Same simple type names may exist in different packages.'], ['Encapsulation', 'Package-private members form an internal package API.'], ['Maintainability', 'Related classes have predictable source locations.'], ['Dependency lookup', 'Sourcepath/classpath roots must locate the required types.'], ['Case sensitivity', 'pkg.A and pkg.a name different types.']])}`),
    section('errors', '11. Common errors and exact repairs', table(['Message / symptom', 'Likely cause', 'Repair'], errors)),
    section('practice', '12. Exam-style practice and answers', `${question('A. Place Helper in ub.cs.tools. Give declaration, source path, output path and binary name. [4]', '<p>package ub.cs.tools; / src/ub/cs/tools/Helper.java / classes/ub/cs/tools/Helper.class / ub.cs.tools.Helper. The src and classes roots are not package segments.</p>')}${question('B. Explain import java.util.* and whether it includes subpackages. [3]', '<p>It allows accessible types directly in java.util to be named simply. It does not import types from subpackages, copy code or install dependencies.</p>')}${question('C. Why can pkg.Tester call B.secret while app.Main cannot? [3]', '<p>secret has no access modifier, so it is package-private. Tester shares pkg. Main belongs to app; importing B does not grant member visibility.</p>')}${question('D. Repair java -classpath classes/pkg Tester.class. [3]', '<p>Use java -classpath classes pkg.Tester. The classpath names the root above package folders; the launch argument is a dotted binary name without an extension.</p>')}${question('E. Compile and run the four classes in this chapter. State expected output. [6]', `${code(command, 'Commands')}<p>pkg.Tester prints Hello from pkg.A, 42, pkg only. app.Main prints Hello from pkg.A, 10.</p>`)}${question('F. Scanner is unresolved even though the JDK is installed. What are two fixes? [2]', '<p>Add import java.util.Scanner; or use java.util.Scanner at every relevant type/constructor use. Both name the same class.</p>')}`),
    section('summary', '13. Test-ready summary and mastery check', `<p class="summary">${summary}</p>${list(['I can separate package declaration, import and access modifier.', 'I can translate dots to directories below a specified root.', 'I can explain specific/wildcard/fully qualified alternatives.', 'I can identify the main class and run it without an extension.', 'I can diagnose naming, lookup and visibility errors separately.'])}`),
  ] };
}

function createCondensedGuides() {
  return REGISTRY.map((meta) => ['linear', 'binary'].includes(meta.kind) ? searchGuide(meta) : SORT_INFO[meta.kind] ? sortGuide(meta) : packageGuide(meta));
}

const REFERENCE_CHAPTERS = {
  linear: ['searching', 'linear-array', 'linear-definition', 'linear-simple', 'linear-idea', 'linear-movements', 'linear', 'linear-variants', 'linear-examples', 'linear-properties', 'linear-complexity', 'linear-when', 'linear-mistakes', 'linear-summary', 'linear-practice'],
  binary: ['searching', 'binary-array', 'binary-definition', 'binary-simple', 'binary-idea', 'binary-movements', 'binary', 'binary-descending', 'binary-examples', 'binary-properties', 'binary-complexity', 'binary-when', 'binary-mistakes', 'binary-summary', 'binary-practice', 'search-summary'],
  bubble: ['why-sort', 'sort-map', 'bubble-array', 'bubble-definition', 'bubble-simple', 'bubble-idea', 'bubble-movements', 'bubble', 'bubble-descending', 'bubble-examples', 'bubble-properties', 'bubble-complexity', 'bubble-when', 'bubble-mistakes', 'bubble-summary', 'bubble-practice'],
  selection: ['why-sort', 'sort-map', 'selection-array', 'selection-definition', 'selection-simple', 'selection-idea', 'selection-movements', 'selection', 'selection-descending', 'selection-examples', 'selection-properties', 'selection-complexity', 'selection-when', 'selection-mistakes', 'selection-summary', 'selection-practice'],
  insertion: ['why-sort', 'sort-map', 'array', 'definition', 'simple', 'idea', 'movements', 'trace', 'table', 'java', 'recursive', 'insertion-descending', 'insertion-test', 'examples', 'properties', 'complexity', 'when', 'mistakes', 'summary', 'practice'],
  merge: ['why-sort', 'sort-map', 'merge-array', 'merge-definition', 'merge-simple', 'merge-idea', 'merge-movements', 'merge-sort', 'merge-descending', 'merge-examples', 'merge-properties', 'merge-complexity', 'merge-when', 'merge-mistakes', 'merge-summary', 'merge-practice', 'sort-compare', 'growth'],
  imports: ['array-foundations', 'file-array-app', 'object-sorting', 'packages', 'test1-q2'],
  package: ['packages', 'lab-work', 'lab-marks', 'lab-staff'],
  build: ['packages', 'lab-work', 'lab-marks', 'lab-staff'],
};

const SUPPLEMENTS = {
  linear: [['visual', 'interactive-lab', 'Interactive trace lab'], ['implementation', 'annotated-java', 'Fully annotated Java'], ['recursive', 'recursion-lab', 'Recursive version and call stack'], ['runnable', 'runnable-java', 'Complete runnable Java playground'], ['practice', 'expanded-exam-practice', 'More exam-style practice']],
  binary: [['visual', 'interactive-lab', 'Interactive trace lab'], ['implementation', 'annotated-java', 'Fully annotated Java'], ['recursive', 'recursion-lab', 'Recursive version and call stack'], ['runnable', 'runnable-java', 'Complete runnable Java playground'], ['practice', 'expanded-exam-practice', 'More exam-style practice']],
  bubble: [['visual', 'interactive-lab', 'Interactive trace lab'], ['implementation', 'annotated-java', 'Fully annotated Java'], ['recursive', 'recursion-lab', 'Recursive version and call stack'], ['runnable', 'runnable-java', 'Complete runnable Java playground'], ['practice', 'expanded-exam-practice', 'More exam-style practice']],
  selection: [['visual', 'interactive-lab', 'Interactive trace lab'], ['implementation', 'annotated-java', 'Fully annotated Java'], ['recursive', 'recursion-lab', 'Recursive version and call stack'], ['runnable', 'runnable-java', 'Complete runnable Java playground'], ['practice', 'expanded-exam-practice', 'More exam-style practice']],
  insertion: [['visual', 'interactive-lab', 'Interactive trace lab'], ['implementation', 'annotated-java', 'Fully annotated Java'], ['recursive', 'recursion-lab', 'Recursive version and call stack'], ['runnable', 'runnable-java', 'Complete runnable Java playground'], ['practice', 'expanded-exam-practice', 'More exam-style practice']],
  merge: [['visual', 'interactive-lab', 'Interactive call-and-return lab'], ['mechanics', 'merge-mechanics-lab', 'Every merge movement in slow motion'], ['implementation', 'annotated-java', 'Fully annotated Java'], ['recursive', 'recursion-lab', 'Recursion tree and live call stack'], ['runnable', 'runnable-java', 'Complete runnable Java playground'], ['practice', 'expanded-exam-practice', 'More exam-style practice']],
  imports: [['workflow', 'interactive-workflow', 'Interactive name-resolution workflow'], ['implementation', 'annotated-java', 'Fully annotated Java and commands'], ['examples', 'expanded-worked-cases', 'More worked package cases'], ['practice', 'expanded-exam-practice', 'More exam-style practice']],
  package: [['workflow', 'interactive-workflow', 'Interactive package workflow'], ['implementation', 'annotated-java', 'Fully annotated Java and commands'], ['examples', 'expanded-worked-cases', 'More worked package cases'], ['practice', 'expanded-exam-practice', 'More exam-style practice']],
  build: [['workflow', 'interactive-workflow', 'Interactive compile-and-run workflow'], ['implementation', 'annotated-java', 'Fully annotated Java and commands'], ['examples', 'expanded-worked-cases', 'More worked package cases'], ['practice', 'expanded-exam-practice', 'More exam-style practice']],
};

function softenPastPaperLabels(html) {
  return html
    .replace(/Test 1 question/gi, 'Exam-style question')
    .replace(/Test 1/gi, 'the past paper');
}

function referenceChapter(kind) {
  return REFERENCE_CHAPTERS[kind].map((id) => {
    const item = REFERENCE_SECTIONS[id];
    if (!item) throw new Error(`Missing reference section ${id} for ${kind}`);
    const exampleNotice = id === 'array' || id.endsWith('-array') ? '<p class="fine-print"><strong>Detailed reference example:</strong> this part introduces its own input, shown below. The opening whole-run map and guided walkthrough keep their original input throughout; each later worked example states its new input explicitly.</p>' : '';
    return { ...item, title: softenPastPaperLabels(item.title), body: exampleNotice + softenPastPaperLabels(item.body), raw: true, reference: true };
  });
}

function supplementalSections(guide) {
  const byId = new Map(guide.sections.map((item) => [item.id, item]));
  return SUPPLEMENTS[guide.kind].map(([sourceId, id, title]) => {
    const source = byId.get(sourceId);
    if (!source) throw new Error(`Missing supplemental section ${sourceId} for ${guide.kind}`);
    return section(id, title, `<div class="studio">${source.body}</div>`);
  });
}

export function createGuides() {
  const guides = createCondensedGuides().map((guide) => {
    const { kind } = guide;
    const overview = MAP_KIND(kind) ? algorithmOverview(kind) : packageOverview(kind);
    const sources = new Map(guide.sections.map(s => [s.id, s]));
    const extension = (source, id, title) => section(id, title, `<div class="studio">${sources.get(source).body}</div>`);
    const map = section('visual-map', 'The whole process at a glance', `${MAP_KIND(kind) ? '' : `<p class="lede">${guide.summary}</p><p>Think of a package as a class address. The package, filename, source root and compiled root have distinct jobs.</p>`}<div class="studio">${overview.body}</div>`);
    const walkthrough = section('interactive-walkthrough', 'Guided walkthrough: predict the next major step', `<div class="studio">${overview.walkthrough}</div>`);
    const trace = section('concise-trace', 'The trace at a glance', `<div class="studio">${overview.trace}</div>`);
    let sections;
    if (MAP_KIND(kind)) {
      const refs = referenceChapter(kind);
      const take = (ids) => ids.map(id => refs.find(s => s.id === id)).filter(Boolean);
      const ids = kind === 'insertion' ? ['array', 'definition', 'simple', 'idea', 'movements'] : [`${kind}-array`, `${kind}-definition`, `${kind}-simple`, `${kind}-idea`, `${kind}-movements`];
      const concepts = take(ids);
      const implementation = take(kind === 'insertion' ? ['trace', 'table', 'java', 'recursive'] : [kind === 'merge' ? 'merge-sort' : kind]);
      const explained = take(kind === 'insertion' ? ['properties', 'complexity', 'when'] : [`${kind}-properties`, `${kind}-complexity`, `${kind}-when`]);
      const placed = new Set([...concepts, ...implementation, ...explained].map(s => s.id));
      const rest = refs.filter(s => !placed.has(s.id));
      sections = [algorithmIntroduction(kind), map, concepts[0], algorithmReason(kind),
        ...(kind === 'merge' ? [section('final-merge', 'Build the final row, one value at a time', finalMergeWalkthrough(sort('merge', MERGE_INPUT)))] : []),
        walkthrough, trace,
        ...(kind === 'merge' ? [section('merge-lanes', 'A closer look at one merge return', `<div class="studio">${focusedMergeLesson(sort('merge', MERGE_INPUT))}</div>`)] : []),
        section('bar-explanation', 'Read the algorithm as a bar graph', `<div class="studio">${barLesson(kind)}</div>`),
        extension('implementation', 'annotated-java', 'Fully annotated Java: connect each line to the movement'),
        section('topic-quiz', 'Topic quiz: try it yourself', topicQuiz(kind)),
        ...concepts.slice(1), ...implementation,
        extension('recursive', 'recursion-lab', 'Recursion, calls and returns'),
        ...(kind === 'merge' ? [extension('mechanics', 'merge-mechanics-lab', 'Inside a merge: pointers, temporary output and copy-back')] : []),
        extension('runnable', 'runnable-java', 'A complete runnable Java example'),
        ...explained, ...rest,
        extension('examples', 'expanded-worked-cases', 'More worked cases: edge cases, duplicates and descending order'),
        extension('practice', 'expanded-exam-practice', 'Exam-style practice with worked answers')];
    } else {
      // Split the original package chapter only at heading boundaries; retain
      // every paragraph, table, command and example in its original order.
      const parts = REFERENCE_SECTIONS.packages.body.split(/(?=<h3\b)/);
      const refs = parts.map((body, i) => ({ id: `package-reference-${i}`, title: body.match(/<h[23][^>]*>(.*?)<\/h[23]>/)?.[1].replace(/<[^>]+>/g, '') || 'Package foundations', body, raw: true, reference: true }));
      sections = [map, extension('definition', 'concept', 'The concept, plain language and vocabulary'), walkthrough, trace,
        ...refs, extension('implementation', 'annotated-java', 'Fully annotated Java and commands'),
        extension('visibility', 'visibility', 'Imports and access: different responsibilities'),
        extension('properties', 'properties', 'Properties and practical cost'),
        extension('examples', 'expanded-worked-cases', 'Five worked package cases'),
        extension('errors', 'errors', 'Common errors and exact repairs'),
        extension('practice', 'expanded-exam-practice', 'Exam-style practice with worked answers'),
        ...referenceChapter(kind).filter(s => s.id !== 'packages').map(s => ({ ...s, title: `Application: ${s.title}` }))];
    }
    if (!MAP_KIND(kind)) sections.push(section('topic-quiz', 'Topic quiz: test your understanding', topicQuiz(kind)));
    // Preserve the full reference, but do not present several competing traces
    // or alternate implementations at once on a student's first reading.
    const optional = new Set(['concise-trace', 'merge-lanes', 'bar-explanation', 'recursion-lab', 'merge-mechanics-lab', 'runnable-java', 'expanded-worked-cases', 'expanded-exam-practice']);
    sections = sections.map(item => optional.has(item.id) || (MAP_KIND(kind) && (item.reference || item.id === 'interactive-walkthrough')) ? { ...item, optional: true } : item);
    return { ...guide, summary: ALGORITHM_INTRODUCTIONS[kind]?.goal || guide.summary, referenceSha256: REFERENCE_SHA256, sections };
  });
  // Resolve the reference's cross-topic anchors after splitting the book.
  const destinations = new Map();
  for (const guide of guides) for (const s of guide.sections) {
    for (const id of [s.id, ...[...s.body.matchAll(/\bid="([^"]+)"/g)].map(m => m[1])]) if (!destinations.has(id)) destinations.set(id, guide);
  }
  for (const guide of guides) {
    const local = new Set(guide.sections.flatMap(s => [s.id, ...[...s.body.matchAll(/\bid="([^"]+)"/g)].map(m => m[1])]));
    guide.sections = guide.sections.map(s => ({ ...s, body: s.body.replace(/href="#([^"]+)"/g, (all, id) => {
      if (local.has(id)) return all;
      const target = destinations.get(id);
      if (!target) throw new Error(`Unresolved reference anchor ${id} in ${guide.id}`);
      return `href="../${target.chapter}/${target.slug}.html#${id}"`;
    }) }));
  }
  return guides;
}

function MAP_KIND(kind) { return ['linear', 'binary', 'bubble', 'selection', 'insertion', 'merge'].includes(kind); }
